server:
  port: 8082

spring:
  application:
    name: product-service
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:user
    username: sa
    password:
    driver-class-name: org.h2.Driver
  liquibase:
    enabled: true
    change-log: classpath:changelog/changelog-master.xml
  h2:
    console:
      enabled: true